linters:
  csslint: {  }
  checkstyle:
    config: './checkstyle.xml'
  eslint:
    config: './eslint.config'
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
fixers:
  enable: true
