linters:
  csslint: {  }
  checkstyle:
    config: './google_checks.xml'
  eslint:
    config: './eslintrc.json'
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
fixers:
  enable: true
